#!/bin/bash
# Auto-generated by TeamIDE
# Lists repos in the local pool (~/TeamIDE/)

POOL="${TEAMIDE_HOME:-$HOME/TeamIDE}"

if [ ! -d "$POOL" ]; then
  exit 0
fi

REPOS=()
for owner_dir in "$POOL"/*/; do
  owner=$(basename "$owner_dir")
  # Skip hidden dirs and data dir
  case "$owner" in .*|.data) continue;; esac
  [ -d "$owner_dir" ] || continue

  for repo_dir in "$owner_dir"*/; do
    [ -d "$repo_dir/.git" ] || continue
    REPOS+=("$owner/$(basename "$repo_dir")")
  done
done

if [ ${#REPOS[@]} -eq 0 ]; then
  exit 0
fi

echo "=== Repo Pool (~/TeamIDE/) ==="
echo "Available repos:"
for r in "${REPOS[@]}"; do
  echo "  - $r"
done

exit 0
