#!/bin/bash
# Auto-generated by TeamIDE
# Injects TeamIDE CLI awareness into Claude Code sessions

if ! command -v teamide &>/dev/null; then
  exit 0
fi

echo "=== TeamIDE CLI ==="
echo ""
echo "Commands:"
echo "  teamide login / logout / whoami"
echo "  teamide workspace list / use <id>"
echo "  teamide deploy [branch] -w <id>"
echo "  teamide stop [branch] -w <id>"
echo "  teamide status -w <id>"
echo "  teamide logs [branch] -w <id>"
echo "  teamide env list -w <id> -b <branch>"
echo "  teamide env set <K=V> -w <id> -b <branch>"
echo "  teamide env get <key> -w <id> -b <branch>"
echo "  teamide env delete <key> -w <id> -b <branch>"
echo ""

# Show auth status
AUTH=$(teamide whoami 2>&1)
if echo "$AUTH" | grep -q "Authenticated"; then
  WS=$(echo "$AUTH" | grep "Default workspace:" | sed 's/Default workspace: //')
  echo "Auth: authenticated"
  if [ -n "$WS" ]; then
    echo "Default workspace: $WS"
  fi
else
  echo "Auth: not logged in (run 'teamide login')"
fi

exit 0
